apiVersion: v1
kind: Service
metadata:
  name: react-wellness-service
spec:
  type: NodePort
  selector:
    app: react-wellness-app
  ports:
    - port: 80        # service port
      targetPort: 80  # container port
      nodePort: 30080 # Kubernetes exposes here
